# Generated by Django 5.1.3 on 2024-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
