# Generated by Django 5.1.3 on 2024-11-28 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_job_delivery_date_alter_job_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2024, 11, 30)),
        ),
    ]
