# Generated by Django 5.1.3 on 2024-11-28 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_job_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 28)),
        ),
    ]
